# this will start a new node container
# it will run node index.js
# it will expose port 3002

version: '3'
services:
  node:
    image: node:latest
    container_name: node
    volumes:
      - .:/app
    working_dir: /app
    command: node index.js
    ports:
      - "3002:3002"

